server:
  port: 80


oauth:
  wx:
    appid: fdafadfdsa
    appsecret: fadfdafd
  callback:
     http: http://fadsfds.dfad.fdfsad.com/wxcallback

# Spring Config
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth?characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: fdsafads
    password: dfadfdsafds
    driver-class-name: com.mysql.jdbc.Driver
#  web:
#   resources:
#    static-locations: classpath:/templates,classpath:/static
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点1
# MyBatis 配置
mybatis:
  type-aliases-package: com.spring.wx.oauth.entity      # Entity 扫描的包名
  configuration:
    cache-enabled: true
